name = "navsphere"
compatibility_date = "2026-01-31"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liWSkijIIvfFwOJM"
GITHUB_OWNER = "zhongguomeng"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://dh.364066648.xyz/api/auth"
NEXT_PUBLIC_API_URL="https://dh.364066648.xyz/"
